### ISSUE TITLE
How to animate paper progress manually? 

### ISSUE THREAD

**Issue by rycastaneda** [PolymerElements/paper-progress#37]
Hi! is there a document where we can see how to animate the progress manually?

**Comment by keanulee** [comment]
Not sure what you mean exactly, but from the docs (https://elements.polymer-project.org/elements/paper-progress):

Add the class `transiting` to a paper-progress to animate the progress bar when
the value changed. You can also customize the transition:

``` css
    paper-progress {
      --paper-progress-transition-duration: 0.08s;
      --paper-progress-transition-timing-function: ease;
      --paper-progress-transition-transition-delay: 0s;
    }
```

Here is a JS Bin example - http://jsbin.com/socaviwuda/edit?html,output
